services:
  database:
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=gateway
      - POSTGRES_PASSWORD=gateway
      - POSTGRES_USER=gateway
    image: postgres:9.6.20
    restart: always

  gateway:
    environment:
      - DATABASE_MIGRATIONS=file://app/migrations
      - DATABASE_URL=postgres://gateway:gateway@database:5432/gateway?sslmode=disable
      - DOMAIN=http://localhost:8080
      - PORT=8080
      - WEB_APP=http://localhost:3000
    image: gateway
